on:
 workflow_dispatch:

name: Update Swagger HTML
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npx @redocly/cli build-docs https://api.clickhouse.cloud/v1 --output static/en/cloud/manage/api/swagger.html
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add static/en/cloud/manage/api/swagger.html
          git commit -m "generated HTML"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GENERATE_PRS }}
